<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.groupeisi</groupId>
        <artifactId>springmvc-jsp</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>ihm</artifactId>
    <packaging>war</packaging>
    <name>ihm Maven Webapp</name>
    <url>http://maven.apache.org</url>
    <dependencies>
        <dependency>
            <groupId>com.groupeisi</groupId>
            <artifactId>common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.groupeisi</groupId>
            <artifactId>metier</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.groupeisi</groupId>
                    <artifactId>common</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
    <build>
        <finalName>ihm</finalName>
    </build>
</project>
